# Generated by Django 6.0 on 2025-12-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetail',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
