# Generated by Django 4.2.11 on 2025-12-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_personaldetail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='doc_type',
            field=models.CharField(choices=[('resume', 'Resume'), ('cv', 'CV')], default='resume', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(default='My Document', max_length=100),
        ),
    ]
